# Generated by Django 5.1.15 on 2026-06-08 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('home_team', models.CharField(max_length=120)),
                ('away_team', models.CharField(max_length=120)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('external_match_id', models.CharField(blank=True, max_length=64)),
                ('actual_home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['game_week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GameWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=160)),
                ('date_range_label', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('locked', 'Locked'), ('results_in', 'Results in'), ('finalised', 'Finalised')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['season', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FixtureGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=160)),
                ('goals', models.PositiveSmallIntegerField(default=1)),
                ('is_penalty', models.BooleanField(default=False)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='competition.fixture')),
            ],
            options={
                'ordering': ['fixture', 'player_name'],
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='game_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competition.gameweek'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('join_week', models.PositiveSmallIntegerField(default=1)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competition.season')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.gameweek')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_hours', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('game_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='competition.gameweek')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ScorerPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('player_name', models.CharField(blank=True, max_length=160)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer_picks', to='competition.entry')),
            ],
            options={
                'ordering': ['entry', 'position'],
            },
        ),
        migrations.AddField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_weeks', to='competition.season'),
        ),
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('s1_total', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to='competition.participant')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to='competition.season')),
            ],
        ),
        migrations.CreateModel(
            name='TotalGoalsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_goals_prediction', to='competition.entry')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=300)),
                ('correct_answer', models.BooleanField(blank=True, null=True)),
                ('game_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competition.gameweek')),
            ],
            options={
                'ordering': ['game_week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrueFalseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tf_answers', to='competition.entry')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.truefalsequestion')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s3', models.IntegerField(default=0)),
                ('s4', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('is_non_entry_default', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('game_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='competition.gameweek')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='competition.participant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('game_week', 'order')},
        ),
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pred_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_predictions', to='competition.entry')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.fixture')),
            ],
            options={
                'unique_together': {('entry', 'fixture')},
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['participant', 'game_week'], name='competition_partici_4b67ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('participant', 'game_week')},
        ),
        migrations.AlterUniqueTogether(
            name='reminderlog',
            unique_together={('game_week', 'participant', 'window_hours')},
        ),
        migrations.AlterUniqueTogether(
            name='scorerpick',
            unique_together={('entry', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'season')},
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['season', 'week_number'], name='competition_season__d74336_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together={('season', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='seasonscore',
            index=models.Index(fields=['season', 'total'], name='competition_season__c9c0f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonscore',
            unique_together={('participant', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='truefalsequestion',
            unique_together={('game_week', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='truefalseanswer',
            unique_together={('entry', 'question')},
        ),
        migrations.AddIndex(
            model_name='weeklyscore',
            index=models.Index(fields=['game_week', 'total'], name='competition_game_we_6562fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyscore',
            unique_together={('participant', 'game_week')},
        ),
    ]
