# Generated by Django 5.1.15 on 2026-06-08 15:41

from django.db import migrations, models


def backfill_teams(apps, schema_editor):
    """Seed the lookup from team names already present on existing fixtures."""
    Fixture = apps.get_model("competition", "Fixture")
    Team = apps.get_model("competition", "Team")
    seen = {t.name.lower() for t in Team.objects.all()}
    for fixture in Fixture.objects.all():
        for name in (fixture.home_team, fixture.away_team):
            name = (name or "").strip()
            if name and name.lower() not in seen:
                Team.objects.create(name=name)
                seen.add(name.lower())


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('external_team_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(backfill_teams, migrations.RunPython.noop),
    ]
