# Generated by Django 5.1.15 on 2026-06-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scorerpick',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('club', models.CharField(blank=True, max_length=120)),
                ('national_team', models.CharField(blank=True, max_length=120)),
                ('external_player_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='competition_full_na_a87248_idx')],
            },
        ),
        migrations.AddField(
            model_name='fixturegoal',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='competition.player'),
        ),
        migrations.AddField(
            model_name='scorerpick',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks', to='competition.player'),
        ),
    ]
