# Generated by Django 5.1.15 on 2026-06-09 16:25

from django.db import migrations, models


def backfill_questions(apps, schema_editor):
    """Seed the bank from question text already used on existing game weeks."""
    TrueFalseQuestion = apps.get_model("competition", "TrueFalseQuestion")
    QuestionTemplate = apps.get_model("competition", "QuestionTemplate")
    seen = {t.text.lower() for t in QuestionTemplate.objects.all()}
    for q in TrueFalseQuestion.objects.all():
        text = (q.text or "").strip()
        if text and text.lower() not in seen:
            QuestionTemplate.objects.create(text=text)
            seen.add(text.lower())


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_gameweek_is_international_scorerpick_needs_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.RunPython(backfill_questions, migrations.RunPython.noop),
    ]
